### ISSUE TITLE
Rebuild bindings and apply new params

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-celo#121]
Rebuild new bindings from solidity updates that should be provided by @lastperson.
## Implementation details

resulting signature of Execute method should be looking something like 
```solidity
function executeProposal(
    uint8 chainID,
    uint64 depositNonce,
    bytes memory data,
    bytes32 resourceID,
    bytes memory blockHeaderRLP,
    bytes blockHashPrefix,
    bytes memory blockHashSuffix,
    bytes memory blockHashBLSHints,
    bytes memory blockHashSignature,
    bytes memory aggregatePublicKey,
    bytes memory merkleKey,
    bytes memory merkleNodes
)
```
regenerate bindigns and add params that were added in previous issues
## Testing details

E2E could be falling here bcs celo-boostrap will contain old smart contracts. 
Ask @P1sar to rebuild it.

**Comment by waymobetta** [comment]
Found `executeProposal` in `Bridge.sol` from [celo-solidity](https://github.com/ChainSafe/chainbridge-celo-solidity/) showing outdated function signature? 

```solidity
 function executeProposal(
        uint8 chainID,
        uint64 depositNonce,
        bytes memory data,
        bytes32 resourceID,
        bytes memory signatureHeader,
        bytes memory aggregatePublicKey,
        bytes32 hashedMessage,
        bytes32 rootHash,
        bytes memory key,
        bytes memory nodes
    ) 
```

Maybe a branch has not been merged yet?

**Comment by P1sar** [comment]
Smart contracts were not changed yet. Thats why these issue is in the very end of milestone.
